swagger: '2.0'

info:
  version: "1.0.0"
  title: "AMT - gamification"
  description:
    "The API specification for the AMT - gamification project. All endpoints are implicitely prefixed by __/api__ for the sake of readability."

consumes:
  - application/json
produces:
  - application/json

paths:
  /register/:
    post:
      summary: "Registers a gamified application."
      parameters:
        - name: body
          in: body
          description: "The info needed to create the credentials of the application."
          required: true
          schema:
            $ref: "#/definitions/Credentials"
      responses:
        201:
          description: "Successful operation."

  /auth/:
    post:
      summary: "Logs an application in."
      parameters:
        - name: body
          in: body
          description: "The credentials of the application."
          required: true
          schema:
            $ref: "#/definitions/Credentials"
      responses:
        200:
          description: "Successful operation."
        400:
          description: "Error code todo: Application already authenticated."
        401:
          description: "- Error code 4: The application does not exist.\n- Error code 5: Authentication failed. \n- Error code todo: JWT invalid.\n- Error code todo: Invalid JWT format."
          
  /badges/:
    get:
      summary: "Retrieves all badges for the current application."
      responses:
        200:
          description: "Successful operation."
          schema:
            type: array
            items:
              $ref: "#/definitions/Badge"
      security:
          - JWT: []
    
    post:
      summary: "Creates a new badge."
      parameters:
        - name: body
          in: body
          description: "The info needed to create the badge."
          required: true
          schema:
            $ref: "#/definitions/Badge"
      responses:
        201:
          description: "Successful operation."
          headers:
            Location:
              description: "URI of newly created object."
              type: string
      security:
        - JWT: []
          
  /badges/{id}/:
    get:
      summary: "Retrieves a given badge."
      parameters:
        - name: id
          in: path
          description: "The id of the badge."
          required: true
          type: number
      responses:
        200:
          description: "Successful operation."
          schema:
            $ref: "#/definitions/Badge"
      security:
        - JWT: []
            
    put:
      summary: "Updates a given badge."
      parameters:
        - name: id
          in: path
          description: "The id of the badge."
          required: true
          type: number
          
        - name: body
          in: body
          description: "The new info of the badge."
          schema:
            $ref: "#/definitions/Badge"
      responses:
        200:
          description: "Successful operation."
      security:
        - JWT: []
          
    patch:
      summary: "Partially updates a given badge."
      parameters:
        - name: id
          in: path
          description: "The id of the badge."
          required: true
          type: number
          
        - name: body
          in: body
          description: "The new info of the badge."
          required: false
          schema:
            $ref: "#/definitions/Badge"
      responses:
        200:
          description: "Successful operation."
      security:
        - JWT: []
          
    delete:
      summary: "Deletes a given badge."
      parameters:
        - name: id
          in: path
          description: "The id of the badge."
          required: true
          type: number
      responses:
        200:
          description: "Successful operation."
      security:
        - JWT: []
  
  /events/:
    post:
      summary: "Creates an event."
      description: "Creates an event triggered by an action made by an user of the application. If the user does not exist in the platform, he will be created."
      parameters:
        - name: body
          in: body
          description: "The new info of the badge."
          required: false
          schema:
            $ref: "#/definitions/Event"
      responses:
        201:
          description: "Successful operation."
      security:
        - JWT: []

  /users/:
    get:
      summary: "Gets the awards of all the users."
      description: "Get all the users of the current application with their bagdes and points awarded."
      responses:
        200:
          description: "Successful operation."
          schema:
            $ref: "#/definitions/User"
      security:
        - JWT: []
          
  /users/{id}/:
    get:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
          
  /pointScales/:
     post:
       summary: "todo"
       responses:
         200:
           description: ""
       security:
        - JWT: []
  
  /pointScales/{id}/:
    get:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
          
    put:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
          
    patch:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
          
    delete:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
  
  /rules/events/:
    post:
      summary: "todo"
      parameters:
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/EventRule"
      responses:
        200:
          description: ""
      security:
        - JWT: []
    
  /rules/events/{id}/:
    put:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
          
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/EventRule"
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
          
    patch:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
          
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/EventRule"
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
          
    delete:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
  
  /rules/triggers/:
    post:
      summary: "todo"
      parameters:
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/TriggerRule"  
      responses:
        200:
          description: ""
      security:
        - JWT: []
        
  /rules/triggers/{id}/:
    put:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
          
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/TriggerRule"
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
          
    patch:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
          
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/TriggerRule"
      responses:
        200:
          description: "todo"
      security:
        - JWT: []
          
    delete:
      summary: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
      security:
        - JWT: []

securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Credentials:
    description: "The credentials of an application."
    type: object
    properties:
      username:
        type: string
        description: "The username of the application."
      password:
        type: string
        description: "The password of the application."
        
  Badge:
    description: "A badge in an application."
    type: object
    properties:
      name:
        type: string
        description: "The name of the badge."
        
  PointsOnPointScale:
    description: "How many points an user has on a given point scale."
    type: object
    properties:
      pointScale:
        type: string
        description: "The point scale."
      points:
        type: number
        description: "How many points are on the point scale."
  
  Event:
    description: "An event created when an user does something on the application."
    type: object
    properties:
      type: 
        type: string
        description: "The type of the event."
      username: 
        type: string
        description: "The username of the user."
        
  User:
    description: "An user doing various actions in an application."
    type: object
    properties:
      username:
        type: string
        description: "The username of the user."
      badges:
        description: "The badges awarded to the user."
        type: array
        items:
          $ref: "#/definitions/Badge"
      points:
        description: "The points received by the user."
        type: array
        items:
          $ref: "#/definitions/PointsOnPointScale"

  EventRule:
    description: "A rule applied on event creation."
    type: object
    properties:
      name:
        type: string
        description: "the name of the rule"
      event:
        type: string
        description: "the event on which the rule is applied"
      pointScale:
        type: string
        description: "the the point scale on which the rule is applied"
      pointsGiven:
        type: number
        description: "how many points are given on the point scale"

  TriggerRule:
    description: "A rule applied on point scale change."
    type: object
    properties:
      name:
        type: string
        description: "the name of the rule"
      badgeAwarded:
        type: string
        description: "the badge awarded when rule condition matched"
      pointScale:
        type: string
        description: "the the point scale on which the rule is applied"
      limit:
        type: number
        description: "the point limit to award the badge"
      aboveLimit:
        type: boolean
        description: "whether the badge is given above or below point limit"
      