swagger: '2.0'

info:
  version: "1.0.0"
  title: "AMT - gamification"
  description:
    "The API specification for the AMT - gamification project. All endpoints are implicitely prefixed by __/api__ for the sake of readability."
    
consumes:
  - application/json
produces:
  - application/json

paths:
  /register/:
    post:
      description: "todo"
      parameters:
        - name: body
          in: body
          description: "The credentials of the application."
          required: true
          schema:
            $ref: "#/definitions/Credentials"
              
      responses:
        201:
          description: "Successful operation."

  /auth/:
    post:
      description: "Logs an application in."
      parameters:
        - name: body
          in: body
          description: "The credentials of the application."
          required: true
          schema:
            $ref: "#/definitions/Credentials"
      responses:
        200:
          description: "Successful operation."
        401:
          description: "- Error code 4: The application does not exist. \n- Error code 5: Authentication failed."
          
  /badges/:
    post:
     description: "todo"
     responses:
      200:
        description: ""
  
  /events/:
     post:
       description: "todo"
       responses:
        200:
          description: ""

  /users/:
    get:
      description: "todo"
      responses:
        200:
          description: "Successful operation. todo"
          
  /users/{id}/:
    get:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
          
  /pointScales/:
     post:
       description: "todo"
       responses:
        200:
          description: ""
  
  /pointScales/{id}/:
    get:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
          
    put:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
          
    patch:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
          
    delete:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
  
  /rules/events/:
    post:
      description: "todo"
      parameters:
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/EventRule"
      responses:
        200:
          description: ""
    
  /rules/events/{id}/:
    put:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
          
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/EventRule"
      responses:
        200:
          description: "todo"
          
    patch:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
          
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/EventRule"
      responses:
        200:
          description: "todo"
          
    delete:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"
  
  /rules/triggers/:
    post:
      description: "todo"
      parameters:
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/TriggerRule"  
      responses:
        200:
          description: ""
        
  /rules/triggers/{id}/:
    put:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
          
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/TriggerRule"
      responses:
        200:
          description: "todo"
          
    patch:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
          
        - name: body
          in: body
          description: "todo"
          schema:
            $ref: "#/definitions/TriggerRule"
      responses:
        200:
          description: "todo"
          
    delete:
      description: "todo"
      parameters:
        - name: id
          in: path
          description: "todo"
          required: true
          type: number
      responses:
        200:
          description: "todo"

definitions:
  Credentials:
    type: object
    properties:
      username:
        type: string
        description: "the username of the application"
      password:
        type: string
        description: "the password of the application"

  EventRule:
    type: object
    properties:
      name:
        type: string
      event:
        type: string
      pointScale:
        type: string
      pointsGiven:
        type: number

  TriggerRule:
    type: object
    properties:
      name:
        type: string
      badgeAwarded:
        type: string
      pointScale:
        type: string
      limit:
        type: number
      aboveLimit:
        type: boolean
      