version: '2.1'

services:
  db:
    image: mariadb:10
    command: mysqld --sql_mode="STRICT_ALL_TABLES" --character-set-server=utf8 --collation-server=utf8_unicode_ci
    env_file: ./deployment/env

    ports:
      - "${GAMIFICATION_DB_PORT:-3306}:3306"

  app:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile-app

    env_file: ./deployment/env

    links:
     - db
    ports:
     - "${GAMIFICATION_APP_PORT:-8080}:8080"
