version: '2'
services:
  mysql:
    build: ./images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"
  maven:
    build: ./images/maven
    links:
     - mysql:db
    ports:
     - "9090:8080"
