version: '2'
services:
  mysql:
    build: ./images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"
  open-jdk:
    build: ./images/open-jdk
    ports:
     - "9090:8080"
    links:
     - mysql:db
